project:
  type: website
  output-dir: docs
  
website:
  title: "amara-brown.github.io"
  navbar:
    right:
      - text: website
        icon: suit-heart-fill
        href: https://amara-brown.github.io/
        
    left: 
      - href: data.qmd
        text: Data
        
format:
  html:
    css: style.css
    toc: true

editor: visual

