project:
  type: website
  output-dir: docs
  
format:
  html:
    css: style.css
    toc: true
  
website:
  navbar:
    right:
      - text: website
        icon: suit-heart-fill
        href: https://amara-brown.github.io/
        
    left: 
      - href: index.qmd
        text: Home

editor: visual

